steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/$BRANCH_NAME/" ]; then
        ls
        cd Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/$BRANCH_NAME
        terraform init
      else
        ls
        for dir in Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/$BRANCH_NAME/" ]; then
        cd Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/$BRANCH_NAME
        terraform plan
      else
        for dir in Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/*/
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/$BRANCH_NAME/" ]; then
        cd Proyecto1/LuisMora_P1/proyecto/terraform/enviroments/$BRANCH_NAME      
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]
